### ISSUE TITLE
docker-compose version too high

### ISSUE THREAD

**Issue by m4rcu5nl** [m4rcu5nl/ansible-role-docker#2]
Make sure docker-compose version 1.9.0 is installed using pip. It takes care of other dependencies (like docker-py)

```
  # Specifically install docker-compose 1.9.0 to avoid errors when working 
  # with the Docker module in current Ansible release.
  - name: Install docker-compose version 1.9.0 using pip
    pip:
      name: docker-compose
      state: present
      version: '1.9.0'

#  - name: 'Install docker-py and docker-compose from Pip'
#    pip:
#      name: "{{ item }}"
#      state: present
#    with_items:
#      - "docker-py"
#      - "docker-compose"
```
